export const ERRORCODE = {
    USRAUT0001: "Invalid Mobile Number or Password ",
    USRAUT0005: "Invalid Login Attempts exceeded",
    USRAUT0007: "Logged in with default password. Please reset your password",
    USRAUT0010: "Mobile is Required",
    USRAUT0012: "OTP is Required",
    USRAUT0013: "txnId is Required",
    USRAUT0014: "Invalid OTP",
    USRAUT0015: "Your account does not exist. Please register.",
    USRAUT0018: "Generate OTP failed",
    USRAUT0019: "Confirm OTP failed",
    USRAUT0020: "Something went wrong",
    USRAUT0021: "Invalid Display Name",

    USRMOB0000: "Phone Number should be of 10 digits ",
    USRPRF0001: "This mobile number is not registered ",
    USRPRF0002: "Phone Number should be of 10 digits ",
    USRPRF0003: "OTP should be of 6 digits",
    USRPRF0004: "New password cannot be same as current password ",
    USRPRF0005: "Invalid OTP",
    USRPRF0006: "User is not known.",
    USRPRF0007: "Enter the OTP to help us verify your identity.",
    USRPRF0008: "Invalid OTP",
    USRPRF0009: "No user found .",
    USRPRF0010: "New MobileNumber is required",
    USRPRF0011: "Phone Number should be of 10 digits ",
    USRPRF0012: "OTP should be of 6 digits",
    USRPRF0013: "New password cannot be same as current password ",
    USRPRF0014: "User is not known",
    USRPRF0015: "User Name Must be between 2-30 characters ",
    USRPRF00016: "The new mobile number is already registered.",
    USRPRF00017: "New Mobile Number cannot be same as Current Mobile Number",
    USRPRF00018: "User is not known.",
    USRPRF00019: "New Password cannot be empty. ",
    USRPRF00020: "Current Password does not match. ",
    USRPRF00021: "New password cannot be same as current password ",
    USRPRF00022: "Password is invalid as per password policy ",
    USRPRF00023: "Captcha Invalid",
    USRPRF00024: "Captcha Timed Out",
    USRPRF00025: "Required missing parameters",
    USRPRF00026: "User Name Must be between 2-30 characters ",
    USRPRF00027: "TxnId required ",
    USRPRF00028: "Confirm Password required ",
    USRPRF00029: "Confirm Password and New password must be same",
    USRPRF00030: "Invalid Forgot Password Request",
    USRPRF00031: "User Id required",
    USRPRF00032: "Invalid User Details",

    CONFIG0001: "Set Application Category",
    CONFIG0002: "Application Category already exist",
    CONFIG0003: "Invalid User",
    CONFIG0004: "Application category is not set",
    CONFIG0020: "Passwords do not match",
    CONFIG0021: "Password require atleast 8 digit and sholud be alpha - numeric",
    CONFIG0022: "Phone number is required",
    CONFIG0023: "Invalid Mobile Number",
 
};
