CREATE TYPE USER_STATUS AS ENUM (0, 1, 2, 3, 4);
CREATE TYPE ROLE_STATUS AS ENUM (0, 1, 2);
CREATE TYPE DEPARTMENT_STATUS AS ENUM (0, 1, 2);
CREATE TYPE MENU_STATUS AS ENUM (0, 1, 2);
CREATE TYPE APP_STATUS AS ENUM (0, 1, 2);